### ISSUE TITLE
Strange `ResourceWarning`

### ISSUE THREAD

**Issue by WilliamJamieson** [spacetelescope/roman_datamodels#150]
Background: in PR #142, the use of `pytest-openfiles` was switched out for catching `ResourceWarnings` directly with `pytest`. This should work because Python will issue a `ResourceWarning` if a file handle is left open when the file goes out of scope (that is leaving a file open). For the most part this will work as a drop in replacement; however, under certain circumstances `pytest` is unable to raise the `ResourceWarning` as an error, resulting in a `PytestUnraisableExceptionWarning`. Typically, these are raised when testing error messages using the `pytest.raises` context manger. The interesting thing is that these `PytestUnraisableExceptionWarnings` are being issued for things not caught by `pytest-openfiles`. For example, in #143 some new warnings show up in the [CI](https://github.com/spacetelescope/roman_datamodels/actions/runs/4659291564/jobs/8245992937?pr=143#step:10:70):
```
tests/test_filetype.py::test_filetype
  /home/runner/work/roman_datamodels/roman_datamodels/.tox/test-xdist/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
  
  Traceback (most recent call last):
    File "/home/runner/work/roman_datamodels/roman_datamodels/tests/test_filetype.py", line 19, in test_filetype
      file_8 = filetype.check(open(DATA_DIRECTORY / "fake.asdf"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/runner/work/roman_datamodels/roman_datamodels/tests/data/fake.asdf' mode='r' encoding='UTF-8'>
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_models.py::test_make_saturation
  /home/runner/work/roman_datamodels/roman_datamodels/.tox/test-xdist/lib/python3.11/site-packages/_pytest/unraisableexception.py:[78](https://github.com/spacetelescope/roman_datamodels/actions/runs/4659291564/jobs/8245992937?pr=143#step:10:79): PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
  
  Traceback (most recent call last):
    File "/home/runner/work/roman_datamodels/roman_datamodels/.tox/test-xdist/lib/python3.11/site-packages/jsonschema/validators.py", line 909, in resolve_from_url
      document = self.store[url]
                 ~~~~~~~~~~^^^^^
    File "/home/runner/work/roman_datamodels/roman_datamodels/.tox/test-xdist/lib/python3.11/site-packages/jsonschema/_utils.py", line 28, in __getitem__
      return self.store[self.normalize(uri)]
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  KeyError: 'asdf://stsci.edu/datamodels/roman/schemas/reference_files/ref_common-1.0.0'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/runner/work/roman_datamodels/roman_datamodels/.tox/test-xdist/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
      node = self.get_single_node()
             ^^^^^^^^^^^^^^^^^^^^^^
  ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/pytest-of-runner/pytest-0/popen-gw0/test_add_model_attribute0/testreadnoise2.asdf'>
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_open.py::test_path_input
  /home/runner/work/roman_datamodels/roman_datamodels/.tox/test-xdist/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.11.2/x64/lib/python3.11/contextlib.py", line 2[89](https://github.com/spacetelescope/roman_datamodels/actions/runs/4659291564/jobs/8245992937?pr=143#step:10:90), in helper
      return _GeneratorContextManager(func, args, kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/pytest-of-runner/pytest-0/popen-gw0/test_asdf_in_fits_error0/AsdfInFits.fits'>
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
All of these warnings are fixed by #149.

However, these are not the issue here. If one runs the tests twice in a row, a new `PytestUnraisableExceptionWarning` appears, such as:
```
tests/test_models.py::test_make_saturation
  /Users/wjamieson/.pyenv/versions/3.11.2/envs/roman_datamodels/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
  
  Traceback (most recent call last):
    File "/Users/wjamieson/.pyenv/versions/3.11.2/envs/roman_datamodels/lib/python3.11/site-packages/jsonschema/validators.py", line 909, in resolve_from_url
      document = self.store[url]
                 ~~~~~~~~~~^^^^^
    File "/Users/wjamieson/.pyenv/versions/3.11.2/envs/roman_datamodels/lib/python3.11/site-packages/jsonschema/_utils.py", line 28, in __getitem__
      return self.store[self.normalize(uri)]
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  KeyError: 'asdf://stsci.edu/datamodels/roman/schemas/reference_files/saturation-1.0.0'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/Users/wjamieson/.pyenv/versions/3.11.2/envs/roman_datamodels/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
      node = self.get_single_node()
             ^^^^^^^^^^^^^^^^^^^^^^
  ResourceWarning: unclosed file <_io.BufferedReader name='/private/var/folders/wr/y4mz2y553jn8wwblt_9wtn240002qx/T/pytest-of-wjamieson/pytest-191/test_add_model_attribute0/testreadnoise2.asdf'>
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

Some observations about this

1. The test that emits the `PytestUnraisableExceptionWarning` is not consistent, except that it is in a test following: https://github.com/spacetelescope/roman_datamodels/blob/626e0da697614cefaef3b26d06fc3f528e2c7dab/tests/test_models.py#L555-L571
2. The precise error (in the above example the `KeyError`) that is emitted, while the `PytestUnraisableExceptionWarning` occurs is also inconsistent.
3. What will make the warning consistently disappear is removing: https://github.com/spacetelescope/roman_datamodels/blob/626e0da697614cefaef3b26d06fc3f528e2c7dab/tests/test_models.py#L570-L571 from `test_add_model_attribute`.
4. This `PytestUnraisableExceptionWarning` only gets emitted when running the entire test sweet twice in a row. That is I cannot reproduce the issue in isolation as the tests are currently (even if I isolate to just `tests/test_models.py`). However, if I remove the `pytest.raises` context from line 570 (meaning `test_add_model_attribute` will fail), then I can reproduce the warning by just running `tests/test_models.py`. This warning will again occur in some later test.

The error appears to be that the `testreadnoise2.asdf` file is not being closed. If one plays around with the test and closing the underlying files when an error is raised, one can switch the offending file to `testreadnoise.asdf` (the first file in the test).

This seems like a very deep bug, and it is a bit disturbing that I cannot even isolate it to a single run of the unit tests (let alone a single test module or test). I know it is real because I can reproduce it by following the steps above.

My testing was done in a new environment created by installing `roman_datamodels` using PR #149's branch on Python 3.11.2.

**Comment by WilliamJamieson** [comment]
Hmm, well when I rebuilt my environment with python 3.11.3 this issue disappeared, and when I tried rebuilding again with python 3.11.2 again this issue disappeared. My guess is there was something corrupting the environment in some strange way.

**Comment by WilliamJamieson** [comment]
This seems to be randomly reappearing in the CI, see: 

- https://github.com/spacetelescope/roman_datamodels/actions/runs/4734250649/jobs/8402903268
- https://github.com/spacetelescope/roman_datamodels/actions/runs/4734265219/jobs/8402937511

Reopening to track the issue.

**Comment by WilliamJamieson** [comment]
Another hit: https://github.com/spacetelescope/roman_datamodels/actions/runs/4747285939/jobs/8432000102?pr=157

**Comment by WilliamJamieson** [comment]
Interesting development, I can reproduce locally this bug (for now) using the changes at 3a7511a48bac3f68ca0756e33494809a635c50d3.
